name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-test1-workflow]

jobs:
  process_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Triggered Workflow Step
        run: echo "This is the triggered workflow"
